[package]
name = "rust-miniecho"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "miniecho"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
# for tests
assert_cmd = "2" 
predicates = "3"